spring:
  application:
    name: users-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/emicorp_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
